apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: tz6fymt6u-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/tz6fymt6u-dotnet-basic-gitops